# Generated by Django 5.1.3 on 2024-11-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomModel',
            new_name='Room',
        ),
    ]
