# Generated by Django 5.1.3 on 2024-12-11 17:47

import booking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_created_at_booking_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(booking.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
